### ISSUE TITLE
pipeline does not work due to missing tools

### ISSUE THREAD

**Issue by ayoraind** [CSU-KangHu/HiTE#25]
Hi @CSU-KangHu 

Thank you for your tool. I am trying to run the pipeline, using the test data as input (demo/genome.fa). I followed the instructions on running it via Nextflow. I tried to use either of the docker, singularity, or conda containers. However, I keep getting an error on missing tools. 
The following is an example code using the docker container

```
docker pull kanghu/hite:3.0.0

nextflow run main.nf -profile docker --genome demo/genome.fa --outdir test_out -c test.config
```

The `test.config` file contains the following:

```
process.resourceLimits = [ memory: 8.GB, cpus: 4, time: 1.h ]
```

However, I encountered the following error

```
---Check if rmblastn is installed.

---Check if LTR_retriever is installed.

Execution cancelled -- Finishing pending tasks before exit
WARN: Undocumented setting `docker.userEmulation` is not supported any more - please remove it from your config
ERROR ~ Error executing process > 'LTR (genome.fa)'

Caused by:
  Process `LTR (genome.fa)` terminated with an error exit status (1)


Command executed:
python3 /workspace/HiTE/module/judge_LTR_transposons.py      -g genome.fa --ltrharvest_home /workspace/HiTE/bin/LTR_HARVEST_parallel --ltrfinder_home /workspace/HiTE/bin/LTR_FINDER_parallel-master      -t 4 --tmp_output_dir test_out      --recover 0 --miu 1.3e-8 --use_NeuralTE 1 --is_wicker 0     --NeuralTE_home /workspace/HiTE/bin/NeuralTE --TEClass_home /workspace/HiTE/classification
  
  cp test_out/confident_ltr_cut.fa ./

Command exit status:
  1

Command output:
  (empty)
  Command error:
  Traceback (most recent call last):
    File "/workspace/HiTE/module/judge_LTR_transposons.py", line 135, in <module>
      log = Logger(tmp_output_dir + '/HiTE_ltr.log', level='debug')
    File "/workspace/HiTE/module/Util.py", line 35, in __init__
      th = handlers.TimedRotatingFileHandler(filename=filename,when=when,backupCount=backCount,encoding='utf-8')
    File "/opt/conda/envs/HiTE/lib/python3.8/logging/handlers.py", line 200, in __init__
      BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
    File "/opt/conda/envs/HiTE/lib/python3.8/logging/handlers.py", line 55, in __init__
      logging.FileHandler.__init__(self, filename, mode, encoding, delay)
    File "/opt/conda/envs/HiTE/lib/python3.8/logging/__init__.py", line 1147, in __init__
      StreamHandler.__init__(self, self._open())
    File "/opt/conda/envs/HiTE/lib/python3.8/logging/__init__.py", line 1176, in _open
      return open(self.baseFilename, self.mode, encoding=self.encoding)
  FileNotFoundError: [Errno 2] No such file or directory: 'test_out/HiTE_ltr.log'
  
  Work dir:
  /workspace/HiTE/work/33/0f095ba99cde2905b6cabfe85813fa

Container:
  kanghu/hite:3.2.0

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

I see similar errors when I used Singularity instead of docker.

With conda, I could not create the conda environment due to incompatibility issues with the tools

The `conda env create --name HiTE -f environment.yml` yields:

```
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package biopython-1.78-py38h7f8727e_0 is excluded by strict repo priority
  - package python-3.8.16-h7a1cb2a_2 is excluded by strict repo priority
  - package keras-2.6.0-pyhd3eb1b0_0 is excluded by strict repo priority
  - package scikit-learn-1.2.0-py38h6a678d5_1 is excluded by strict repo priority
  - package tensorflow-2.6.0-cpu_py37hc107814_2 requires tensorflow-base 2.6.0 cpu_py37hc5ef7b8_2, but none of the providers can be installed
  - package numpy-1.19.5-py38h8246c76_3 requires python_abi 3.8.* *_cp38, but none of the providers can be installed
```

I guess the containers need an update to solve compatibility issues. 

I look forward to your response.

**Comment by CSU-KangHu** [comment]
Hi @ayoraind,

Thank you very much for using HiTE. In response to your issue, we have updated the Docker image and tested it to ensure it runs smoothly. Please download the latest image.

Regarding the conda installation issue, we have tested the installation on different machines and successfully set up the environment. The problems you are experiencing may be related to your specific environment.

I also noticed that you seem to be developing a new Nextflow pipeline and are trying to integrate HiTE, which looks great! If you need any assistance, please feel free to reach out to me.

Best,
Kang

**Comment by ayoraind** [comment]
Hi @CSU-KangHu 

Thank you for your response. The docker issue has been solved. I ran Nextflow (using the same command that was used previously) on the demo/genome.fasta files and encountered a different error (I wasn't expecting any error when using the demo files). 

```
executor >  local (7)
[6d/9bea94] EnvCheck (envcheck)     [100%] 4 of 4 ✔
[97/a45541] LTR (genome.fa)         [100%] 1 of 1, failed: 1 ✘
[ff/828d3b] OtherTE (genome.fa)     [100%] 1 of 1 ✔
[-        ] MergeLTROther           -
[78/6befbf] SplitGenome (genome.fa) [100%] 1 of 1 ✔
[-        ] coarseBoundary          -
[-        ] TIR                     -
[-        ] Helitron                -
[-        ] Non_LTR                 -
[-        ] BuildLib                -
[-        ] AnnotateGenome          -
[-        ] Benchmarking            -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'LTR (genome.fa)'

Caused by:
  Process `LTR (genome.fa)` terminated with an error exit status (1)


Command executed:

  python3 /workspace/HiTE/module/judge_LTR_transposons.py      -g genome.fa --ltrharvest_home /workspace/HiTE/bin/LTR_HARVEST_parallel --ltrfinder_home /workspace/HiTE/bin/LTR_FINDER_parallel-master      -t 4 --recover 0 --use_NeuralTE 1 --miu 1.3e-8      --NeuralTE_home /workspace/HiTE/bin/NeuralTE --TEClass_home /workspace/HiTE/classification      --is_wicker 0

Command exit status:
  1
  Command output:
  
  Fri Nov  1 04:29:14 UTC 2024  Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.
  
  Fri Nov  1 04:29:19 UTC 2024  Intact LTR-RT found: 1
  
  Fri Nov  1 04:29:19 UTC 2024  Module 6: Start to analyze truncated LTR-RTs...
                                Truncated LTR-RTs without the intact version will be retained in the LTR-RT library.
                                Use -notrunc if you don't want to keep them.
  
  Fri Nov  1 04:29:19 UTC 2024  1 truncated LTR-RTs found
  Fri Nov  1 04:29:20 UTC 2024  1 truncated LTR sequences have added to the library
  
  Fri Nov  1 04:29:20 UTC 2024  Module 5: Start to remove DNA TE and LINE transposases, and remove plant protein sequences...
                                Total library sequences: 4
                                Fri Nov  1 04:29:23 UTC 2024  Retained clean sequence: 4
  
  Fri Nov  1 04:29:23 UTC 2024  Sequence clustering for genome.rename.fa.ltrTE ...
  Fri Nov  1 04:29:23 UTC 2024  Unique lib sequence: 4
  
  Fri Nov  1 04:29:23 UTC 2024  Module 6: Start to remove nested insertions in internal regions...
  Fri Nov  1 04:29:24 UTC 2024  Raw internal region size (bit): 12407
                                Clean internal region size (bit): 12407
  
  Fri Nov  1 04:29:24 UTC 2024  Sequence number of the redundant LTR-RT library: 4
                                The redundant LTR-RT library size (bit): 12911
                                Fri Nov  1 04:29:24 UTC 2024  Module 8: Start to make non-redundant library...
  
  Fri Nov  1 04:29:24 UTC 2024  Final LTR-RT library entries: 3
                                Final LTR-RT library size (bit): 12908
  
  Fri Nov  1 04:29:24 UTC 2024  Total intact LTR-RTs found: 1
                                Total intact non-TGCA LTR-RTs found: 1
  
  Fri Nov  1 04:29:24 UTC 2024  All analyses were finished!
  
  ##############################
  ####### Result files #########
  ##############################
  Table output for intact LTR-RTs (detailed info)
        genome.rename.fa.pass.list (All LTR-RTs)
        genome.rename.fa.nmtf.pass.list (Non-TGCA LTR-RTs)
        genome.rename.fa.pass.list.gff3 (GFF3 format for intact LTR-RTs)
  
  LTR-RT library
        genome.rename.fa.LTRlib.redundant.fa (All LTR-RTs with redundancy)
        genome.rename.fa.LTRlib.fa (All non-redundant LTR-RTs)
        genome.rename.fa.nmtf.LTRlib.fa (Non-TGCA LTR-RTs)

Command error:
                                Truncated LTR-RTs without the intact version will be retained in the LTR-RT library.
                                Use -notrunc if you don't want to keep them.
                                 Fri Nov  1 04:29:19 UTC 2024  1 truncated LTR-RTs found
  Fri Nov  1 04:29:20 UTC 2024  1 truncated LTR sequences have added to the library
  
  Fri Nov  1 04:29:20 UTC 2024  Module 5: Start to remove DNA TE and LINE transposases, and remove plant protein sequences...
                                Total library sequences: 4
  Fri Nov  1 04:29:23 UTC 2024  Retained clean sequence: 4
  
  Fri Nov  1 04:29:23 UTC 2024  Sequence clustering for genome.rename.fa.ltrTE ...
  Fri Nov  1 04:29:23 UTC 2024  Unique lib sequence: 4
  
  Fri Nov  1 04:29:23 UTC 2024  Module 6: Start to remove nested insertions in internal regions...
  Fri Nov  1 04:29:24 UTC 2024  Raw internal region size (bit): 12407
                                Clean internal region size (bit): 12407
                                Fri Nov  1 04:29:24 UTC 2024  Sequence number of the redundant LTR-RT library: 4
                                The redundant LTR-RT library size (bit): 12911
  
  Fri Nov  1 04:29:24 UTC 2024  Module 8: Start to make non-redundant library...
  
  Fri Nov  1 04:29:24 UTC 2024  Final LTR-RT library entries: 3
                                Final LTR-RT library size (bit): 12908
  
  Fri Nov  1 04:29:24 UTC 2024  Total intact LTR-RTs found: 1
                                Total intact non-TGCA LTR-RTs found: 1
                                 Fri Nov  1 04:29:24 UTC 2024  All analyses were finished!
  
  ##############################
  ####### Result files #########
  ##############################
  
  Table output for intact LTR-RTs (detailed info)
        genome.rename.fa.pass.list (All LTR-RTs)
        genome.rename.fa.nmtf.pass.list (Non-TGCA LTR-RTs)
        genome.rename.fa.pass.list.gff3 (GFF3 format for intact LTR-RTs)
        LTR-RT library
        genome.rename.fa.LTRlib.redundant.fa (All LTR-RTs with redundancy)
        genome.rename.fa.LTRlib.fa (All non-redundant LTR-RTs)
        genome.rename.fa.nmtf.LTRlib.fa (Non-TGCA LTR-RTs)
  2024-11-01 04:29:24,608 - /workspace/HiTE/module/Util.py[line:689] - DEBUG: LTR_retriever running time: 13.86947 s
  2024-11-01 04:29:24,608 - /workspace/HiTE/module/judge_LTR_transposons.py[line:176] - INFO: Running time of step0.2: 13.86979 s
  2024-11-01 04:29:24,656 - /workspace/HiTE/module/judge_LTR_transposons.py[line:230] - DEBUG: python /workspace/HiTE/bin/NeuralTE/src/Classifier.py --data intact_LTR.fa --use_TSD 0 --model_path /workspace/HiTE/bin/NeuralTE/models/NeuralTE_model.h5 --outdir NeuralTE_LTR --thread 4 --is_wicker 0
  Traceback (most recent call last):
    File "/workspace/HiTE/module/judge_LTR_transposons.py", line 267, in <module>
      label = intact_LTR_labels[intact_ltr_name]
  KeyError: 'chr_1:462006..466965'

Work dir:
  /workspace/HiTE/work/97/a45541838d5c1127e4d8ee5f1b2c80

Container:
  kanghu/hite:3.2.0

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

**Comment by CSU-KangHu** [comment]
Hi @ayoraind,

I discovered the issue was due to missing executable permissions for some tools in the HiTE directory. Before running the command, please execute:

```bash
cd HiTE && chmod +x tools/* bin/NeuralTE/tools/* bin/LTR_FINDER_parallel-master/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder
```

This should resolve the error you encountered.

I’m not very familiar with Nextflow, but in my tests, I noticed that when running with `nextflow run main.nf -profile docker`, Nextflow still uses my local code, and it seems Docker is only used to provide the required Conda environment. If you have a better solution, please let me know.

**Comment by ayoraind** [comment]
@CSU-KangHu 

Thank you very much. The issue has been resolved.

```
executor >  local (11)
[0b/501404] EnvCheck (envcheck)                     [100%] 4 of 4, cached: 4 ✔
[9d/2bc07a] LTR (genome.fa)                         [100%] 1 of 1 ✔
[f2/8eed6f] OtherTE (genome.fa)                     [100%] 1 of 1 ✔
[74/a129c5] MergeLTROther (1)                       [100%] 1 of 1 ✔
[95/613514] SplitGenome (genome.fa)                 [100%] 1 of 1 ✔
[c1/0ae722] coarseBoundary (genome.cut0.fa)         [100%] 1 of 1 ✔
[b2/ff40c5] TIR (longest_repeats_0.flanked.fa)      [100%] 1 of 1 ✔
[b6/ed6a8a] Helitron (longest_repeats_0.flanked.fa) [100%] 1 of 1 ✔
[bf/4c9e28] Non_LTR (longest_repeats_0.flanked.fa)  [100%] 1 of 1 ✔
[6d/9c4008] BuildLib (1)                            [100%] 1 of 1 ✔
[0b/8bc06b] AnnotateGenome (1)                      [100%] 1 of 1 ✔
[34/99c07d] Benchmarking (1)                        [100%] 1 of 1 ✔

Completed at: 05-Nov-2024 16:08:40
Duration    : 17m 40s
CPU hours   : 2.0 (0% cached)
Succeeded   : 11
Cached      : 4
```
