### ISSUE TITLE
Abnormal intermediate file name in running judge_TIR_transposons.py

### ISSUE THREAD

**Issue by ice-cold** [CSU-KangHu/HiTE#26]
Hi @CSU-KangHu,

Thank you for your useful tool. I'm running the pipeline successfully, but I encountered an error during Step 2.2, which involves determining homology in regions outside the TIR copy boundaries. It seems to be attempting to create an intermediate file with an abnormal filename which a colon ":" (as indicated in the last line).

Could you please provide any solutions for this issue?

Thanks in advance!

Best regards,

yec

2024-11-06 11:47:31,083 - main.py[line:513] - INFO: Start step2.2: determine fine-grained TIR
2024-11-06 11:47:31,083 - main.py[line:528] - DEBUG: cd /media/data/HiTE/./module && python3 /media/data/HiTE/./module/judge_TIR_transposons.py  --seqs /media/G-RAID/Seaweed/Genome_Analysis/green_HiTE/longest_repeats_0.flanked.fa -t 20 --TRsearch_dir /media/data/HiTE/./tools --tmp_output_dir /media/G-RAID/Seaweed/Genome_Analysis/green_HiTE --tandem_region_cutoff 0.5 --ref_index 0 --subset_script_path /media/data/HiTE/./tools/ready_for_MSA.sh --plant 1 --flanking_len 50 --recover 0 --debug 0 -r /media/G-RAID/Seaweed/Genome_Analysis/green_HiTE/Kappaphycus_alvarezii_green.fa --split_ref_dir /media/G-RAID/Seaweed/Genome_Analysis/green_HiTE/ref_chr --prev_TE  /media/G-RAID/Seaweed/Genome_Analysis/green_HiTE/prev_TE.fa
2024-11-06 11:47:31,287 - /media/data/HiTE/./module/judge_TIR_transposons.py[line:150] - INFO: ------get TIR+TSD in copies of candidate TIR
2024-11-06 12:28:34,618 - /media/data/HiTE/./module/judge_TIR_transposons.py[line:157] - INFO: Running time of getting TSD in copies of candidate TIR: 2463.330 s
2024-11-06 12:28:34,619 - /media/data/HiTE/./module/judge_TIR_transposons.py[line:162] - INFO: ------clustering candidate TIR
2024-11-06 12:29:09,105 - /media/data/HiTE/./module/judge_TIR_transposons.py[line:169] - INFO: Running time of clustering candidate TIR: 34.48625 s
2024-11-06 12:29:09,106 - /media/data/HiTE/./module/judge_TIR_transposons.py[line:15] - INFO: determine true TIR
2024-11-06 12:29:09,106 - /media/data/HiTE/./module/judge_TIR_transposons.py[line:16] - INFO: ------flank TIR copy and see if the flanking regions are repeated
2024-11-06 12:29:09,106 - /media/data/HiTE/module/Util.py[line:6910] - INFO: ------Determination of homology in regions outside the boundaries of tir copies
Traceback (most recent call last):
  File "/media/data/HiTE/./module/judge_TIR_transposons.py", line 175, in <module>
    is_transposons(tir_tsd_cons, reference, threads, tmp_output_dir, ref_index, log, subset_script_path, plant, debug, TRsearch_dir, split_ref_dir, is_recover)
  File "/media/data/HiTE/./module/judge_TIR_transposons.py", line 32, in is_transposons
    flank_region_align_v5(input_file, output_file, flanking_len, reference, split_ref_dir, TE_type,
  File "/media/data/HiTE/module/Util.py", line 6986, in flank_region_align_v5
    store_fasta(copy_contigs, cur_member_file)
  File "/media/data/HiTE/module/Util.py", line 1969, in store_fasta
    with open(file_path, 'w') as f_save:
OSError: [Errno 22] Invalid argument: '/media/G-RAID/Seaweed/Genome_Analysis/green_HiTE/tir_copies_0_0/ctg000780_np12121212:811014-811366-tir_12-tsd_TA.blast.bed.fa

**Comment by CSU-KangHu** [comment]
Hi @ice-cold,

Thank you for using HiTE and for pointing out this issue. Since filenames containing ‘:’ usually do not trigger errors, this problem had escaped our notice. We've now modified the `module/Util.py` file. You can either replace this file or re-download the entire project to resolve the issue.

Best,  
Kang

**Comment by ice-cold** [comment]
Thanks for your prompt response, I will try the updated script.

Best,
yec
